# Copyright (c) 2026 Open Device Partnership and Contributors
# SPDX-License-Identifier: Apache-2.0

[package]
# This must be rustapp for now.
name = "rustapp"
version = "0.1.0"
edition = "2021"
description = "Offloading blocking Zephyr calls onto a worker thread pool"
license = "Apache-2.0 or MIT"

[lib]
crate-type = ["staticlib"]

[dependencies]
zephyr = { version = "0.1.0", features = ["executor-zephyr", "async-drivers"] }
zephyr-panic = "0.1.0"
static_cell = "2.1"
embassy-executor = "0.10.0"

[build-dependencies]
zephyr-build = "0.1.0"

[profile.dev]
opt-level = 1
