#
# Copyright (c) 2024 TDK Invensense
#
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_SENSOR=y

# Rust support
CONFIG_RUST=y
CONFIG_RUST_ALLOC=y

# Debug settings
CONFIG_DEBUG=y
CONFIG_MAIN_STACK_SIZE=8192

# Floating point format support
CONFIG_CBPRINTF_FP_SUPPORT=y

# Console settings
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETCHAR_BUFSIZE=16
CONFIG_CONSOLE_PUTCHAR_BUFSIZE=512
